package com.gmail.alexdion93.inventoryequipevent.events;

public enum UpdateCause {
  ARMOR_STAND_GIVE, ARMOR_STAND_SWAP, ARMOR_STAND_TAKE, ARROW_EXHUAST, ARROW_FIRE, ARROW_PICKUP, BLOCK_PLACE, BONE_MEAL,
  BUCKET_CHANGE, DISPENSER_EQUIP, ENTITY_FEED, GAMEMODE_CHANGE, INVENTORY_CLICK, INVENTORY_CLOSE, ITEM_BREAK,
  ITEM_CONSUME, ITEM_DROP, ITEM_PICKUP, HAND_USE, JOIN, LECTURE_GIVE, LECTURE_TAKE, OTHER, PROJECTILE_THROW, RESPAWN,
  RESURRECT, RIGHT_CLICK_EQUIP, TOOL_CHANGE, TOOL_SWAP, VEHICLE_PLACE,
}